# Generated by Django 5.2 on 2025-04-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='village',
            name='healthcare_access',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='village',
            name='infrastructure',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
