# Generated by Django 5.2 on 2025-04-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_app', '0002_remove_village_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='banks_atm_facility',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='village',
            name='electricity_supply_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='green_cover',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='village',
            name='market_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='village',
            name='network_connectivity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='village',
            name='number_of_schools',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='parks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='playgrounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='public_transport',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='village',
            name='renewable_energy_source',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='village',
            name='sanitation_everyday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='village',
            name='street_lighting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='village',
            name='waste_management_everyday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='village',
            name='water_supply_to_every_home',
            field=models.BooleanField(default=False),
        ),
    ]
