# Generated by Django 5.2 on 2025-04-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_app', '0003_village_banks_atm_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='number_of_children',
            field=models.IntegerField(default=0),
        ),
    ]
