# Generated by Django 5.2 on 2025-04-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_app', '0004_village_number_of_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='current_census_population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='previous_census_population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='village_area',
            field=models.FloatField(default=0.0),
        ),
    ]
