# Generated by Django 5.2 on 2025-04-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('village_app', '0005_village_current_census_population_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='population',
        ),
    ]
