# Generated by Django 5.2 on 2025-04-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_app', '0006_remove_village_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='number_of_parks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='number_of_playgrounds',
            field=models.IntegerField(default=0),
        ),
    ]
