# Generated by Django 5.2 on 2025-04-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_app', '0007_village_number_of_parks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='number_of_parks',
        ),
        migrations.RemoveField(
            model_name='village',
            name='number_of_playgrounds',
        ),
        migrations.AddField(
            model_name='village',
            name='MRO',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='village',
            name='district',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='village',
            name='pincode',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='village',
            name='population',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='village',
            name='sarpanch',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='village',
            name='state',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='village',
            name='village_area',
            field=models.FloatField(),
        ),
    ]
