# Generated by Django 5.2 on 2025-04-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_app', '0008_remove_village_number_of_parks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='number_of_hospitals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='petrol_bunks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='village',
            name='post_office_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='village',
            name='MRO',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='village',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='village',
            name='pincode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='village',
            name='sarpanch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='village',
            name='state',
            field=models.CharField(default='', max_length=100),
        ),
    ]
