# Generated by Django 5.2 on 2025-04-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village_app', '0009_village_number_of_hospitals_village_petrol_bunks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='village',
            name='population',
            field=models.IntegerField(default=0),
        ),
    ]
